SET DEFINE OFF;
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (58, 'Заработало!!!', TO_TIMESTAMP('03.02.2019 13:02:23.898000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (34, 'Start the moral preparation for the speedy execution of the test task.', TO_TIMESTAMP('03.02.2019 12:15:00.350000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (35, 'Pay attention to China Mieville creativity. Recommended "Rails"', TO_TIMESTAMP('03.02.2019 12:15:00.396000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (36, 'Continue to maintain the physical form in the power loads', TO_TIMESTAMP('03.02.2019 12:15:00.436000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 1);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (37, 'Look in the pet shop and buy tablets for the dog', TO_TIMESTAMP('03.02.2019 12:15:00.476000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 1);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (38, 'The sister asked to look into the bookstore and check the availability of "1984"', TO_TIMESTAMP('03.02.2019 12:15:00.517000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (39, 'Alas. Absolutely do not understand anything in the set conditions. It is necessary to think', TO_TIMESTAMP('03.02.2019 12:15:00.557000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (40, 'Still do not understand anything. Pretty hard', TO_TIMESTAMP('03.02.2019 12:15:00.598000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (41, 'Maybe pay attention to Spring Boot? Looks interesting', TO_TIMESTAMP('03.02.2019 12:15:00.641000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (42, 'It remains to determine the visualization. Wide choice, very', TO_TIMESTAMP('03.02.2019 12:15:00.685000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 1);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (43, 'Explore the details of entry in html', TO_TIMESTAMP('03.02.2019 12:15:00.728000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (44, 'Try to create the first program to display', TO_TIMESTAMP('03.02.2019 12:15:00.771000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (45, 'Error. I continue to understand nothing. Need to learn the documentation', TO_TIMESTAMP('03.02.2019 12:15:00.814000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 1);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (46, 'More documentation to the god of documentation! The error does not go away', TO_TIMESTAMP('03.02.2019 12:15:00.859000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (47, 'Begins to work out. Difficult, but it becomes more or less clear', TO_TIMESTAMP('03.02.2019 12:15:00.902000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (48, 'Explore the intricacies of the Thymeleaf syntax for displaying data', TO_TIMESTAMP('03.02.2019 12:15:00.946000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (49, 'Problems with displaying the table. I need to test another idea', TO_TIMESTAMP('03.02.2019 12:15:00.989000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (50, 'It turns out. It''s crooked, but it works. It is necessary to repair', TO_TIMESTAMP('03.02.2019 12:15:01.033000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 1);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (51, 'It is necessary to raise information about reading from the database. Important condition', TO_TIMESTAMP('03.02.2019 12:15:01.079000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (52, 'Может быть, попытаться добавить стилизацию?', TO_TIMESTAMP('03.02.2019 12:15:01.120000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (53, 'Да! Действительно работает. Мне нужно добавить фильтр', TO_TIMESTAMP('03.02.2019 12:15:01.160000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (54, 'Проблемы с сортировкой даты. Надо понимать', TO_TIMESTAMP('03.02.2019 12:15:01.201000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (55, 'Готово. Осталось только проверить на ошибки', TO_TIMESTAMP('03.02.2019 12:15:01.239000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
Insert into TEST
   (ID, MESSAGE, DATETIME, DONE)
 Values
   (56, 'И снова добавлю стилизованную красотку', TO_TIMESTAMP('03.02.2019 12:15:01.277000','DD.MM.YYYY fmHH24fm:MI:SS.FF'), 0);
COMMIT;
