--
-- Create Schema Script 
--   Database Version   : 11.2.0.2.0 
--   TOAD Version       : 9.7.2.5 
--   DB Connect String  : XE 
--   Schema             : SPRINGAPP 
--   Script Created by  : SPRINGAPP 
--   Script Created at  : 21.02.2019 15:23:00 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 13        Columns: 14         
--   Sequences: 4 
--   Tables: 6          Columns: 33         Constraints: 12     
--   Triggers: 6 


CREATE SEQUENCE CATEGORIES_ID_SEQ
  START WITH 1200
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


CREATE SEQUENCE ORDERS_ID_SEQ
  START WITH 21
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


CREATE SEQUENCE ORDER_DETAILS_ID_SEQ
  START WITH 21
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


CREATE SEQUENCE PRODUCTS_ID_SEQ
  START WITH 19000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


CREATE TABLE ORDER_DETAILS
(
  ID             INTEGER                        NOT NULL,
  ORDERS_ID      INTEGER                        NOT NULL,
  PRODUCTS_ID    INTEGER                        NOT NULL,
  ITEM_PRICE     NUMBER(19,2),
  ITEM_QUANTITY  INTEGER,
  ITEM_TOTAL     NUMBER(19,2) GENERATED ALWAYS AS ("ITEM_PRICE"*"ITEM_QUANTITY")
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SPRING_SESSION_ATTRIBUTES
(
  SESSION_PRIMARY_ID  CHAR(36 BYTE)             NOT NULL,
  ATTRIBUTE_NAME      VARCHAR2(200 CHAR)        NOT NULL,
  ATTRIBUTE_BYTES     BLOB                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SPRING_SESSION
(
  PRIMARY_ID             CHAR(36 BYTE)          NOT NULL,
  SESSION_ID             CHAR(36 BYTE)          NOT NULL,
  CREATION_TIME          NUMBER(19)             NOT NULL,
  LAST_ACCESS_TIME       NUMBER(19)             NOT NULL,
  MAX_INACTIVE_INTERVAL  NUMBER(10)             NOT NULL,
  EXPIRY_TIME            NUMBER(19)             NOT NULL,
  PRINCIPAL_NAME         VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PRODUCTS
(
  ID             INTEGER                        NOT NULL,
  CATEGORIES_ID  INTEGER                        NOT NULL,
  PART_NUMBER    VARCHAR2(255 BYTE),
  DESCRIPTION    VARCHAR2(255 BYTE),
  SERVICE        VARCHAR2(10 BYTE),
  PRICE          NUMBER(19,2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ORDERS
(
  ID                         INTEGER            NOT NULL,
  SPRING_SESSION_PRIMARY_ID  CHAR(36 BYTE)      NOT NULL,
  STATUS                     INTEGER,
  IS_ACTIVE                  INTEGER,
  CREATED_AT                 TIMESTAMP(6),
  ITEMS_COUNT                INTEGER,
  ITEMS_QUANTITY             INTEGER,
  ORDER_TOTAL                NUMBER(19,2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CATEGORIES
(
  ID         INTEGER                            NOT NULL,
  PARENT_ID  INTEGER                            NOT NULL,
  CATNAME    VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SPRING_SESSION_ATTRIBUTES_PK ON SPRING_SESSION_ATTRIBUTES
(SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX SPRING_SESSION_PK ON SPRING_SESSION
(PRIMARY_ID)
LOGGING
NOPARALLEL;


CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION
(PRINCIPAL_NAME)
LOGGING
NOPARALLEL;


CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION
(EXPIRY_TIME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION
(SESSION_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PRODUCTS__IDX ON PRODUCTS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ORDERS__IDXV1 ON ORDERS
(SPRING_SESSION_PRIMARY_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ORDERS__IDX ON ORDERS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ORDER_ITEMS_PK ON ORDER_DETAILS
(ID)
LOGGING
NOPARALLEL;


CREATE INDEX ORDER_DETAILS__IDXV1 ON ORDER_DETAILS
(PRODUCTS_ID)
LOGGING
NOPARALLEL;


CREATE INDEX ORDER_DETAILS__IDX ON ORDER_DETAILS
(ORDERS_ID)
LOGGING
NOPARALLEL;


CREATE INDEX CATEGORIES__IDX ON CATEGORIES
(PARENT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CATEGORIES__IDXV1 ON CATEGORIES
(ID)
LOGGING
NOPARALLEL;


CREATE OR REPLACE TRIGGER categories_id_trg BEFORE
    INSERT ON categories
    FOR EACH ROW
WHEN (
new.id IS NULL
      )
BEGIN
    :new.id := categories_id_seq.nextval;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER orders_id_trg BEFORE
    INSERT ON orders
    FOR EACH ROW
WHEN (
new.id IS NULL
      )
BEGIN
    :new.id := orders_id_seq.nextval;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER item_price_insert_trg
   BEFORE INSERT OR UPDATE
   ON ORDER_DETAILS    REFERENCING NEW AS new OLD AS old
   FOR EACH ROW
DECLARE
   item_price   order_details.item_price%TYPE;
BEGIN
   SELECT   price
     INTO   item_price
     FROM   products
    WHERE   id = :new.products_id;

   :new.item_price := item_price;
EXCEPTION
   WHEN OTHERS
   THEN
      -- Consider logging the error and then re-raise
      RAISE;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER order_details_id_trg
   BEFORE INSERT
   ON ORDER_DETAILS    FOR EACH ROW
WHEN (
new.id IS NULL
      )
BEGIN
   :new.id := order_details_id_seq.NEXTVAL;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER "ORDERS_TOTAL_TRG" FOR
   DELETE OR INSERT OR UPDATE
   ON springapp.order_details
   REFERENCING NEW AS new OLD AS old
COMPOUND TRIGGER
   v_id   order_details.orders_id%TYPE;
   BEFORE EACH ROW
   IS
   BEGIN
      -- we can read or write to :new or :old in the before each row section
      v_id := :new.orders_id;
   END
   BEFORE EACH ROW;

   AFTER STATEMENT
   IS
   BEGIN
      UPDATE   orders
         SET
               (items_count,
               items_quantity,
               order_total
               ) =
                  (  SELECT   SUM (item_quantity),
                              COUNT (products_id),
                              SUM (item_total)
                       FROM   order_details
                      WHERE   orders_id = v_id
                   GROUP BY   order_details.orders_id);
   END
   AFTER STATEMENT;

END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER products_id_trg BEFORE
    INSERT ON products
    FOR EACH ROW
WHEN (
new.id IS NULL
      )
BEGIN
    :new.id := products_id_seq.nextval;
END;
/
SHOW ERRORS;


ALTER TABLE ORDER_DETAILS ADD (
  CONSTRAINT ORDER_ITEMS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE SPRING_SESSION_ATTRIBUTES ADD (
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK
 PRIMARY KEY
 (SESSION_PRIMARY_ID, ATTRIBUTE_NAME));

ALTER TABLE SPRING_SESSION ADD (
  CONSTRAINT SPRING_SESSION_PK
 PRIMARY KEY
 (PRIMARY_ID));

ALTER TABLE PRODUCTS ADD (
  CONSTRAINT PRODUCTS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE ORDERS ADD (
  CONSTRAINT ORDERS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE CATEGORIES ADD (
  CONSTRAINT CATEGORIES_PK
 PRIMARY KEY
 (ID));

ALTER TABLE ORDER_DETAILS ADD (
  CONSTRAINT ORDER_ITEMS_ORDERS_FK 
 FOREIGN KEY (ORDERS_ID) 
 REFERENCES ORDERS (ID)
    ON DELETE CASCADE,
  CONSTRAINT ORDER_ITEMS_PRODUCTS_FK 
 FOREIGN KEY (PRODUCTS_ID) 
 REFERENCES PRODUCTS (ID)
    ON DELETE CASCADE);

ALTER TABLE SPRING_SESSION_ATTRIBUTES ADD (
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK 
 FOREIGN KEY (SESSION_PRIMARY_ID) 
 REFERENCES SPRING_SESSION (PRIMARY_ID)
    ON DELETE CASCADE);

ALTER TABLE PRODUCTS ADD (
  CONSTRAINT PRODUCTS_CATEGORIES_FK 
 FOREIGN KEY (CATEGORIES_ID) 
 REFERENCES CATEGORIES (ID)
    ON DELETE CASCADE);

ALTER TABLE ORDERS ADD (
  CONSTRAINT ORDERS_SPRING_SESSION_FK 
 FOREIGN KEY (SPRING_SESSION_PRIMARY_ID) 
 REFERENCES SPRING_SESSION (PRIMARY_ID)
    ON DELETE CASCADE);

ALTER TABLE CATEGORIES ADD (
  CONSTRAINT CATEGORIES_CATEGORIES_FK 
 FOREIGN KEY (PARENT_ID) 
 REFERENCES CATEGORIES (ID)
    ON DELETE CASCADE);

