-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2019-03-02 15:03:37 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE categories (
    id          NUMBER(*, 0) NOT NULL,
    parent_id   NUMBER(*, 0) NOT NULL,
    catname     VARCHAR2(255 BYTE) NOT NULL,
    is_root     NUMBER(*, 0)
);

CREATE UNIQUE INDEX categories__idxv1 ON
    categories (
        id
    ASC );

CREATE INDEX categories__idx ON
    categories (
        parent_id
    ASC );

ALTER TABLE categories ADD CONSTRAINT categories_pk PRIMARY KEY ( id );

CREATE TABLE order_details (
    id              NUMBER(*, 0) NOT NULL,
    orders_id       NUMBER(*, 0) NOT NULL,
    products_id     NUMBER(*, 0) NOT NULL,
    item_price      NUMBER(19, 2),
    item_quantity   NUMBER(*, 0),
        item_total      NUMBER(19, 2) AS ( "ITEM_PRICE" * "ITEM_QUANTITY" ) VIRTUAL
);

CREATE INDEX order_details__idx ON
    order_details (
        orders_id
    ASC );

CREATE INDEX order_details__idxv1 ON
    order_details (
        products_id
    ASC );

CREATE UNIQUE INDEX springapp.order_items_pk ON
    order_details (
        id
    ASC );

ALTER TABLE order_details ADD CONSTRAINT order_items_pk PRIMARY KEY ( id );

CREATE TABLE orders (
    id                          NUMBER(*, 0) NOT NULL,
    spring_session_primary_id   CHAR(36 BYTE) NOT NULL,
    status                      NUMBER(*, 0),
    is_active                   NUMBER(*, 0),
    created_at                  TIMESTAMP DEFAULT systimestamp,
    items_count                 NUMBER(*, 0),
    items_quantity              NUMBER(*, 0),
    order_total                 NUMBER(19, 2),
    users_user_id               NUMBER(*, 0) NOT NULL,
    customer_is_guest           NUMBER(*, 0)
);

CREATE UNIQUE INDEX orders__idx ON
    orders (
        id
    ASC );

CREATE UNIQUE INDEX orders__idxv1 ON
    orders (
        spring_session_primary_id
    ASC );

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( id );

CREATE TABLE products (
    id            NUMBER(*, 0) NOT NULL,
    category_id   NUMBER(*, 0) NOT NULL,
    part_number   VARCHAR2(255 BYTE),
    description   VARCHAR2(255 BYTE) NOT NULL,
    service       VARCHAR2(10 BYTE),
    price         NUMBER(19, 2) NOT NULL
);

CREATE UNIQUE INDEX products__idx ON
    products (
        id
    ASC );

ALTER TABLE products ADD CONSTRAINT products_pk PRIMARY KEY ( id );

CREATE TABLE springapp.roles (
    role_id       NUMBER(10) NOT NULL,
    description   VARCHAR2(255 BYTE) DEFAULT NULL,
    name          VARCHAR2(255 BYTE) NOT NULL
);

CREATE UNIQUE INDEX springapp.sys_c007739 ON
    springapp.roles (
        role_id
    ASC );

ALTER TABLE springapp.roles ADD CONSTRAINT roles_pk PRIMARY KEY ( role_id );

CREATE TABLE spring_session (
    primary_id              CHAR(36 BYTE) NOT NULL,
    session_id              CHAR(36 BYTE) NOT NULL,
    creation_time           NUMBER(19) NOT NULL,
    last_access_time        NUMBER(19) NOT NULL,
    max_inactive_interval   NUMBER(10) NOT NULL,
    expiry_time             NUMBER(19) NOT NULL,
    principal_name          VARCHAR2(100 CHAR)
);

CREATE UNIQUE INDEX springapp.spring_session_ix1 ON
    spring_session (
        session_id
    ASC );

CREATE INDEX springapp.spring_session_ix2 ON
    spring_session (
        expiry_time
    ASC );

CREATE INDEX springapp.spring_session_ix3 ON
    spring_session (
        principal_name
    ASC );

CREATE UNIQUE INDEX springapp.spring_session_pk ON
    spring_session (
        primary_id
    ASC );

ALTER TABLE spring_session ADD CONSTRAINT spring_session_pk PRIMARY KEY ( primary_id );

CREATE TABLE spring_session_attributes (
    spring_session_primary_id   CHAR(36 BYTE),
    session_primary_id          CHAR(36 BYTE) NOT NULL,
    attribute_name              VARCHAR2(200 CHAR) NOT NULL,
    attribute_bytes             BLOB NOT NULL
);

CREATE UNIQUE INDEX springapp.spring_session_attributes_pk ON
    spring_session_attributes (
        session_primary_id
    ASC,
        attribute_name
    ASC );

ALTER TABLE spring_session_attributes ADD CONSTRAINT spring_session_attributes_pk PRIMARY KEY ( session_primary_id,
                                                                                                attribute_name );

CREATE TABLE springapp.user_addresses (
    address_id      NUMBER(10) NOT NULL,
    address         VARCHAR2(255 BYTE) NOT NULL,
    city            VARCHAR2(255 BYTE) NOT NULL,
    country         VARCHAR2(255 BYTE) NOT NULL,
    fax             VARCHAR2(255 BYTE) NOT NULL,
    phone           VARCHAR2(255 BYTE) NOT NULL,
    user_id         VARCHAR2(255 BYTE) NOT NULL,
    users_user_id   NUMBER(*, 0) NOT NULL
);

CREATE UNIQUE INDEX springapp.sys_c007750 ON
    springapp.user_addresses (
        address_id
    ASC );

ALTER TABLE springapp.user_addresses ADD CONSTRAINT user_addresses_pk PRIMARY KEY ( address_id );

CREATE TABLE springapp.user_tokens (
    token             VARCHAR2(255 BYTE) NOT NULL,
    expiration_date   TIMESTAMP NOT NULL,
    login_date        TIMESTAMP NOT NULL,
    user_id           VARCHAR2(255 BYTE) NOT NULL,
    users_user_id     NUMBER(*, 0) NOT NULL
);

CREATE UNIQUE INDEX springapp.user_tokens__idx ON
    springapp.user_tokens (
        token
    ASC );

ALTER TABLE springapp.user_tokens ADD CONSTRAINT user_tokens_pk PRIMARY KEY ( token );

CREATE TABLE users (
    user_id         NUMBER(*, 0) NOT NULL,
    email           VARCHAR2(255) NOT NULL,
    first_name      VARCHAR2(255) NOT NULL,
    last_name       VARCHAR2(255),
    password_hash   VARCHAR2(255),
    status          NUMBER(*, 0),
    created_at      TIMESTAMP DEFAULT systimestamp,
    roles_role_id   NUMBER(10) NOT NULL,
    salt            VARCHAR2(255 BYTE) NOT NULL
);

CREATE UNIQUE INDEX users__idx ON
    users (
        user_id
    ASC );

CREATE UNIQUE INDEX users__idxv1 ON
    users (
        email
    ASC );

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( user_id );

ALTER TABLE categories
    ADD CONSTRAINT categories_categories_fk FOREIGN KEY ( parent_id )
        REFERENCES categories ( id )
            ON DELETE CASCADE;

ALTER TABLE order_details
    ADD CONSTRAINT order_items_orders_fk FOREIGN KEY ( orders_id )
        REFERENCES orders ( id )
            ON DELETE CASCADE;

ALTER TABLE order_details
    ADD CONSTRAINT order_items_products_fk FOREIGN KEY ( products_id )
        REFERENCES products ( id );

ALTER TABLE orders
    ADD CONSTRAINT orders_spring_session_fk FOREIGN KEY ( spring_session_primary_id )
        REFERENCES spring_session ( primary_id );

ALTER TABLE orders
    ADD CONSTRAINT orders_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE products
    ADD CONSTRAINT products_categories_fk FOREIGN KEY ( category_id )
        REFERENCES categories ( id )
            ON DELETE CASCADE;

ALTER TABLE spring_session_attributes
    ADD CONSTRAINT spring_session_attributes_fk FOREIGN KEY ( spring_session_primary_id )
        REFERENCES spring_session ( primary_id )
            ON DELETE CASCADE;

ALTER TABLE springapp.user_addresses
    ADD CONSTRAINT user_addresses_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id )
            ON DELETE CASCADE;

ALTER TABLE springapp.user_tokens
    ADD CONSTRAINT user_tokens_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id )
            ON DELETE CASCADE;

ALTER TABLE users
    ADD CONSTRAINT users_roles_fk FOREIGN KEY ( roles_role_id )
        REFERENCES springapp.roles ( role_id )
            ON DELETE CASCADE;

CREATE SEQUENCE categories_id_seq START WITH 1200 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER categories_id_trg BEFORE
    INSERT ON categories
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := categories_id_seq.nextval;
END;
/

CREATE SEQUENCE order_details_id_seq START WITH 1 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER order_details_id_trg BEFORE
    INSERT ON order_details
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := order_details_id_seq.nextval;
END;
/

CREATE SEQUENCE orders_id_seq START WITH 1 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER orders_id_trg BEFORE
    INSERT ON orders
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := orders_id_seq.nextval;
END;
/

CREATE SEQUENCE products_id_seq START WITH 19000 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER products_id_trg BEFORE
    INSERT ON products
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := products_id_seq.nextval;
END;
/

CREATE SEQUENCE springapp.roles_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER springapp.roles_seq_tr BEFORE
    INSERT ON springapp.roles
    FOR EACH ROW
    WHEN ( new.role_id IS NULL )
BEGIN
    :new.role_id := springapp.roles_seq.nextval;
END;
/

CREATE SEQUENCE springapp.user_addresses_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER springapp.user_addresses_seq_tr BEFORE
    INSERT ON springapp.user_addresses
    FOR EACH ROW
    WHEN ( new.address_id IS NULL )
BEGIN
    :new.address_id := springapp.user_addresses_seq.nextval;
END;
/

CREATE SEQUENCE users_user_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER users_user_id_trg BEFORE
    INSERT ON users
    FOR EACH ROW
    WHEN ( new.user_id IS NULL )
BEGIN
    :new.user_id := users_user_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                            18
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
