--
-- Create Schema Script 
--   Database Version   : 11.2.0.2.0 
--   TOAD Version       : 9.7.2.5 
--   DB Connect String  : XE 
--   Schema             : SPRINGAPP 
--   Script Created by  : SPRINGAPP 
--   Script Created at  : 17.04.2019 21:14:19 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 19        Columns: 21         
--   Sequences: 8 
--   Tables: 12         Columns: 73         Constraints: 23     
--   Triggers: 11 


CREATE SEQUENCE CATEGORIES_ID_SEQ
  START WITH 1200
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


CREATE SEQUENCE ORDERS_ID_SEQ
  START WITH 181
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


CREATE SEQUENCE ORDER_ADDRESSES_SEQ
  START WITH 81
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE ORDER_DETAILS_ID_SEQ
  START WITH 201
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


CREATE SEQUENCE PRODUCTS_ID_SEQ
  START WITH 19000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;


CREATE SEQUENCE ROLES_SEQ
  START WITH 21
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE USERS_USER_ID_SEQ
  START WITH 43
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;


CREATE SEQUENCE USER_ADDRESSES_SEQ
  START WITH 21
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE TABLE CATEGORIES
(
  ID         INTEGER                            NOT NULL,
  PARENT_ID  INTEGER                            NOT NULL,
  CATNAME    VARCHAR2(255 BYTE)                 NOT NULL,
  IS_ROOT    INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ORDERS
(
  ID                 INTEGER                    NOT NULL,
  STATUS             INTEGER,
  IS_ACTIVE          INTEGER,
  CREATED_AT         TIMESTAMP(6)               DEFAULT systimestamp(6),
  ITEMS_COUNT        INTEGER,
  ITEMS_QUANTITY     INTEGER,
  ORDER_TOTAL        NUMBER(19,2),
  USERS_USER_ID      INTEGER                    NOT NULL,
  CUSTOMER_IS_GUEST  INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PRODUCTS
(
  ID           INTEGER                          NOT NULL,
  CATEGORY_ID  INTEGER                          NOT NULL,
  PART_NUMBER  VARCHAR2(255 BYTE),
  DESCRIPTION  VARCHAR2(255 BYTE)               NOT NULL,
  SERVICE      VARCHAR2(10 BYTE),
  PRICE        NUMBER(19,2)                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE USERS
(
  USER_ID        INTEGER                        NOT NULL,
  EMAIL          VARCHAR2(255 BYTE)             NOT NULL,
  FIRST_NAME     VARCHAR2(255 BYTE)             NOT NULL,
  LAST_NAME      VARCHAR2(255 BYTE)             NOT NULL,
  PASSWORD_HASH  VARCHAR2(255 BYTE)             NOT NULL,
  STATUS         INTEGER,
  CREATED_AT     TIMESTAMP(6)                   DEFAULT systimestamp(6),
  ROLES_ROLE_ID  INTEGER                        NOT NULL,
  SALT           VARCHAR2(255 BYTE),
  PHONE          VARCHAR2(14 BYTE)              NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ROLES
(
  ROLE_ID      INTEGER                          NOT NULL,
  DESCRIPTION  VARCHAR2(255 BYTE)               DEFAULT NULL,
  NAME         VARCHAR2(255 BYTE)               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE USER_ADDRESSES
(
  ADDRESS_ID     INTEGER                        NOT NULL,
  ADDRESS        VARCHAR2(255 BYTE)             NOT NULL,
  CITY           VARCHAR2(255 BYTE),
  COUNTRY        VARCHAR2(255 BYTE),
  FAX            VARCHAR2(255 BYTE),
  PHONE          VARCHAR2(255 BYTE),
  USERS_USER_ID  INTEGER                        NOT NULL,
  APARTMENT      VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE USER_TOKENS
(
  TOKEN            VARCHAR2(255 BYTE)           NOT NULL,
  EXPIRATION_DATE  TIMESTAMP(6),
  LOGIN_DATE       TIMESTAMP(6)                 DEFAULT systimestamp(6),
  USERS_USER_ID    INTEGER                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SPRING_SESSION
(
  PRIMARY_ID             CHAR(36 BYTE)          NOT NULL,
  SESSION_ID             CHAR(36 BYTE)          NOT NULL,
  CREATION_TIME          NUMBER(19)             NOT NULL,
  LAST_ACCESS_TIME       NUMBER(19)             NOT NULL,
  MAX_INACTIVE_INTERVAL  NUMBER(10)             NOT NULL,
  EXPIRY_TIME            NUMBER(19)             NOT NULL,
  PRINCIPAL_NAME         VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ORDER_ADDRESSES
(
  ID          INTEGER                           NOT NULL,
  CREATED_AT  TIMESTAMP(6)                      DEFAULT systimestamp(6),
  POSTCODE    VARCHAR2(255 BYTE)                DEFAULT NULL,
  PREFIX      VARCHAR2(255 BYTE)                DEFAULT NULL,
  REGION      VARCHAR2(255 BYTE)                DEFAULT NULL,
  REGION_ID   INTEGER                           DEFAULT NULL,
  SUFFIX      VARCHAR2(255 BYTE)                DEFAULT NULL,
  UPDATED_AT  TIMESTAMP(6)                      DEFAULT NULL,
  ORDERS_ID   INTEGER                           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ORDER_PAYMENTS
(
  PAYMENT_ID      INTEGER                       NOT NULL,
  STATUS          INTEGER                       NOT NULL,
  TRANSACTION_ID  VARCHAR2(255 BYTE)            NOT NULL,
  ORDERS_ID       INTEGER                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SPRING_SESSION_ATTRIBUTES
(
  SESSION_PRIMARY_ID  CHAR(36 BYTE)             NOT NULL,
  ATTRIBUTE_NAME      VARCHAR2(200 CHAR)        NOT NULL,
  ATTRIBUTE_BYTES     BLOB                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ORDER_DETAILS
(
  ID             INTEGER                        NOT NULL,
  ORDERS_ID      INTEGER                        NOT NULL,
  PRODUCTS_ID    INTEGER                        NOT NULL,
  ITEM_PRICE     NUMBER(19,2),
  ITEM_QUANTITY  INTEGER,
  ITEM_TOTAL     NUMBER(19,2) GENERATED ALWAYS AS ("ITEM_PRICE"*"ITEM_QUANTITY")
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CATEGORIES__IDXV1 ON CATEGORIES
(ID)
LOGGING
NOPARALLEL;


CREATE INDEX CATEGORIES__IDX ON CATEGORIES
(PARENT_ID)
LOGGING
NOPARALLEL;


CREATE INDEX ORDER_DETAILS__IDX ON ORDER_DETAILS
(ORDERS_ID)
LOGGING
NOPARALLEL;


CREATE INDEX ORDER_DETAILS__IDXV1 ON ORDER_DETAILS
(PRODUCTS_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ORDER_ITEMS_PK ON ORDER_DETAILS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ORDERS__IDX ON ORDERS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PRODUCTS__IDX ON PRODUCTS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX USERS__IDX ON USERS
(USER_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX USERS__IDXV1 ON USERS
(EMAIL)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX USER_TOKENS__IDX ON USER_TOKENS
(TOKEN)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX SPRING_SESSION_PK ON SPRING_SESSION
(PRIMARY_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION
(SESSION_ID)
LOGGING
NOPARALLEL;


CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION
(EXPIRY_TIME)
LOGGING
NOPARALLEL;


CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION
(PRINCIPAL_NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX SPRING_SESSION_ATTRIBUTES_PK ON SPRING_SESSION_ATTRIBUTES
(SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ROLES_PK ON ROLES
(ROLE_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX USER_ADDRESSES_PK ON USER_ADDRESSES
(ADDRESS_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ORDER_PAYMENTS_PK ON ORDER_PAYMENTS
(PAYMENT_ID, ORDERS_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ORDER_ADDRESSES_PK ON ORDER_ADDRESSES
(ID)
LOGGING
NOPARALLEL;


CREATE OR REPLACE TRIGGER "ORDER_DETAILS_ID_TRG" BEFORE
    INSERT ON order_details
    FOR EACH ROW
WHEN (
new.id IS NULL
      )
BEGIN
    :new.id := order_details_id_seq.nextval;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER "ITEM_PRICE_INSERT_TRG" BEFORE
    INSERT OR UPDATE ON order_details
    FOR EACH ROW
DECLARE
    item_price order_details.item_price%TYPE;
BEGIN
    SELECT
        price
    INTO item_price
    FROM
        products
    WHERE
        id = :new.products_id;

    :new.item_price := item_price;
EXCEPTION
    WHEN OTHERS THEN
      -- Consider logging the error and then re-raise
        RAISE;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER "CATEGORIES_ID_TRG" BEFORE
    INSERT ON categories
    FOR EACH ROW
WHEN (
new.id IS NULL
      )
BEGIN
    :new.id := categories_id_seq.nextval;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER "ORDERS_ID_TRG" BEFORE
    INSERT ON orders
    FOR EACH ROW
WHEN (
new.id IS NULL
      )
BEGIN
    :new.id := orders_id_seq.nextval;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER "PRODUCTS_ID_TRG" BEFORE
    INSERT ON products
    FOR EACH ROW
WHEN (
new.id IS NULL
      )
BEGIN
    :new.id := products_id_seq.nextval;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER "ROLES_SEQ_TR" 
 BEFORE INSERT ON roles FOR EACH ROW
WHEN (
NEW.role_id IS NULL
      )
BEGIN
 SELECT roles_seq.NEXTVAL INTO :NEW.role_id FROM DUAL;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER "USER_ADDRESSES_SEQ_TR" 
 BEFORE INSERT ON user_addresses FOR EACH ROW
WHEN (
NEW.address_id IS NULL
      )
BEGIN
 SELECT user_addresses_seq.NEXTVAL INTO :NEW.address_id FROM DUAL;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER "USERS_USER_ID_TRG" 
   BEFORE INSERT
   ON USERS    REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
WHEN (
new.user_id IS NULL
      )
BEGIN
   :new.user_id := users_user_id_seq.NEXTVAL;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER "ORDERS_TOTAL_TRG" 
FOR DELETE OR INSERT OR UPDATE
ON ORDER_DETAILS 
REFERENCING NEW AS NEW OLD AS OLD
COMPOUND TRIGGER
    v_id order_details.orders_id%TYPE;
    BEFORE EACH ROW IS BEGIN
          v_id := :new.orders_id;
    END BEFORE EACH ROW;
    AFTER STATEMENT IS BEGIN
        UPDATE orders
        SET
            ( items_count,
              items_quantity,
              order_total ) = (
                SELECT
                    COUNT(products_id),
                    SUM(item_quantity),
                    SUM(item_total)
                FROM
                    order_details
                WHERE
                    orders_id = v_id
                    AND item_quantity != 0
                GROUP BY
                    order_details.orders_id
            )
        WHERE
            id = v_id;

    END AFTER STATEMENT;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER ORDER_ADDRESSES_UPDT
BEFORE UPDATE
ON ORDER_ADDRESSES 
FOR EACH ROW
WHEN (
NEW.UPDATED_AT IS NULL
      )
DECLARE
BEGIN

:NEW.UPDATED_AT := systimestamp;

END ;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER ORDER_ADDRESSES_SEQ_TR 
 BEFORE INSERT ON order_addresses FOR EACH ROW
WHEN (
NEW.id IS NULL
      )
BEGIN
 SELECT order_addresses_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
SHOW ERRORS;


ALTER TABLE CATEGORIES ADD (
  CONSTRAINT CATEGORIES_PK
 PRIMARY KEY
 (ID));

ALTER TABLE ORDERS ADD (
  CONSTRAINT ORDERS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE PRODUCTS ADD (
  CONSTRAINT PRODUCTS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE USERS ADD (
  CONSTRAINT USERS_PK
 PRIMARY KEY
 (USER_ID));

ALTER TABLE ROLES ADD (
  CONSTRAINT ROLES_PK
 PRIMARY KEY
 (ROLE_ID));

ALTER TABLE USER_ADDRESSES ADD (
  CONSTRAINT USER_ADDRESSES_PK
 PRIMARY KEY
 (ADDRESS_ID));

ALTER TABLE USER_TOKENS ADD (
  CONSTRAINT USER_TOKENS_PK
 PRIMARY KEY
 (TOKEN));

ALTER TABLE SPRING_SESSION ADD (
  CONSTRAINT SPRING_SESSION_PK
 PRIMARY KEY
 (PRIMARY_ID));

ALTER TABLE ORDER_ADDRESSES ADD (
  CONSTRAINT ORDER_ADDRESSES_PK
 PRIMARY KEY
 (ID));

ALTER TABLE ORDER_PAYMENTS ADD (
  CONSTRAINT ORDER_PAYMENTS_PK
 PRIMARY KEY
 (PAYMENT_ID, ORDERS_ID));

ALTER TABLE SPRING_SESSION_ATTRIBUTES ADD (
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK
 PRIMARY KEY
 (SESSION_PRIMARY_ID, ATTRIBUTE_NAME));

ALTER TABLE ORDER_DETAILS ADD (
  CONSTRAINT ORDER_ITEMS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE CATEGORIES ADD (
  CONSTRAINT CATEGORIES_CATEGORIES_FK 
 FOREIGN KEY (PARENT_ID) 
 REFERENCES CATEGORIES (ID)
    ON DELETE CASCADE);

ALTER TABLE ORDERS ADD (
  CONSTRAINT ORDERS_USERS_FK 
 FOREIGN KEY (USERS_USER_ID) 
 REFERENCES USERS (USER_ID));

ALTER TABLE PRODUCTS ADD (
  CONSTRAINT PRODUCTS_CATEGORIES_FK 
 FOREIGN KEY (CATEGORY_ID) 
 REFERENCES CATEGORIES (ID)
    ON DELETE CASCADE);

ALTER TABLE USERS ADD (
  CONSTRAINT USERS_ROLES_FK 
 FOREIGN KEY (ROLES_ROLE_ID) 
 REFERENCES ROLES (ROLE_ID)
    ON DELETE CASCADE);

ALTER TABLE USER_ADDRESSES ADD (
  CONSTRAINT USER_ADDRESSES_USERS_FK 
 FOREIGN KEY (USERS_USER_ID) 
 REFERENCES USERS (USER_ID)
    ON DELETE CASCADE);

ALTER TABLE USER_TOKENS ADD (
  CONSTRAINT USER_TOKENS_USERS_FK 
 FOREIGN KEY (USERS_USER_ID) 
 REFERENCES USERS (USER_ID)
    ON DELETE CASCADE);

ALTER TABLE ORDER_ADDRESSES ADD (
  CONSTRAINT ORDER_ADDRESSES_ORDERS_FK 
 FOREIGN KEY (ORDERS_ID) 
 REFERENCES ORDERS (ID)
    ON DELETE CASCADE);

ALTER TABLE ORDER_PAYMENTS ADD (
  CONSTRAINT ORDER_PAYMENTS_ORDERS_FK 
 FOREIGN KEY (ORDERS_ID) 
 REFERENCES ORDERS (ID));

ALTER TABLE SPRING_SESSION_ATTRIBUTES ADD (
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK 
 FOREIGN KEY (SESSION_PRIMARY_ID) 
 REFERENCES SPRING_SESSION (PRIMARY_ID)
    ON DELETE CASCADE);

ALTER TABLE ORDER_DETAILS ADD (
  CONSTRAINT ORDER_ITEMS_ORDERS_FK 
 FOREIGN KEY (ORDERS_ID) 
 REFERENCES ORDERS (ID)
    ON DELETE CASCADE,
  CONSTRAINT ORDER_ITEMS_PRODUCTS_FK 
 FOREIGN KEY (PRODUCTS_ID) 
 REFERENCES PRODUCTS (ID));

