-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2019-02-23 14:53:11 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE categories (
    id          INTEGER NOT NULL,
    parent_id   INTEGER NOT NULL,
    catname     VARCHAR2(255 BYTE) NOT NULL
)
LOGGING;

CREATE UNIQUE INDEX categories__idxv1 ON
    categories (
        id
    ASC )
        LOGGING;

CREATE INDEX categories__idx ON
    categories (
        parent_id
    ASC )
        LOGGING;

ALTER TABLE categories ADD CONSTRAINT categories_pk PRIMARY KEY ( id );

CREATE SEQUENCE categories_id_seq START WITH 1200 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER categories_id_trg BEFORE
    INSERT ON categories
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := categories_id_seq.nextval;
END;
/
ALTER TABLE springapp.order_details DROP CONSTRAINT order_items_products_fk CASCADE;

DROP INDEX springapp.order_details__idx;

DROP INDEX springapp.order_details__idxv1;

DROP TRIGGER springapp.item_price_insert_trg;

DROP TRIGGER springapp.orders_total_trg;

ALTER TABLE springapp.order_details RENAME TO bcp_order_details;

CREATE TABLE order_details (
    id              INTEGER NOT NULL,
    orders_id       INTEGER NOT NULL,
    products_id     INTEGER NOT NULL,
    item_price      NUMBER(19, 2),
    item_quantity   INTEGER,
        item_total      NUMBER(19, 2) AS ( item_price * item_quantity ) VIRTUAL
)

logging;

CREATE SEQUENCE order_details_id_seq START WITH 1 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER order_details_id_trg BEFORE
    INSERT ON order_details
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := order_details_id_seq.nextval;
END;
/

INSERT INTO order_details (
    id,
    orders_id,
    products_id,
    item_price,
    item_quantity
)
    SELECT
        id,
        orders_id,
        products_id,
        item_price,
        item_quantity
    FROM
        springapp.bcp_order_details;

CREATE INDEX order_details__idx ON
    order_details (
        orders_id
    ASC )
        LOGGING;

CREATE INDEX order_details__idxv1 ON
    order_details (
        products_id
    ASC )
        LOGGING;

ALTER TABLE order_details ADD CONSTRAINT order_items_pk PRIMARY KEY ( id );

CREATE OR REPLACE TRIGGER springapp.item_price_insert_trg BEFORE
    INSERT OR UPDATE ON order_details
    FOR EACH ROW
DECLARE
    item_price order_details.item_price%TYPE;
BEGIN
    SELECT
        price
    INTO item_price
    FROM
        products
    WHERE
        id = :new.products_id;

    :new.item_price := item_price;
EXCEPTION
    WHEN OTHERS THEN
      -- Consider logging the error and then re-raise
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER springapp.orders_total_trg FOR
    INSERT OR UPDATE OR DELETE ON order_details
COMPOUND TRIGGER
    v_id order_details.orders_id%TYPE;
    BEFORE EACH ROW IS BEGIN
      -- we can read or write to :new or :old in the before each row section
        v_id := :new.orders_id;
    END BEFORE EACH ROW;
    AFTER STATEMENT IS BEGIN
        UPDATE orders
        SET
            ( items_count,
              items_quantity,
              order_total ) = (
                SELECT
                    SUM(item_quantity),
                    COUNT(products_id),
                    SUM(item_total)
                FROM
                    order_details
                WHERE
                    orders_id = v_id
                    AND item_quantity != 0
                GROUP BY
                    order_details.orders_id
            )
        WHERE
            id = v_id;

    END AFTER STATEMENT;
END;
/
ALTER TABLE springapp.orders DROP CONSTRAINT orders_users_fk CASCADE;

ALTER TABLE springapp.orders DROP CONSTRAINT orders_pk CASCADE;

DROP INDEX springapp.orders__idx;

DROP INDEX springapp.orders__idxv1;

ALTER TABLE springapp.orders RENAME TO bcp_orders;

CREATE TABLE orders (
    id                          INTEGER NOT NULL,
    spring_session_primary_id   CHAR(36 BYTE) NOT NULL,
    status                      INTEGER,
    is_active                   INTEGER,
    created_at                  TIMESTAMP DEFAULT systimestamp,
    items_count                 INTEGER,
    items_quantity              INTEGER,
    order_total                 NUMBER(19, 2),
    users_user_id               INTEGER NOT NULL
)

logging;

CREATE SEQUENCE orders_id_seq START WITH 1 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER orders_id_trg BEFORE
    INSERT ON orders
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := orders_id_seq.nextval;
END;
/

INSERT INTO orders (
    id,
    spring_session_primary_id,
    status,
    is_active,
    created_at,
    items_count,
    items_quantity,
    order_total,
    users_user_id
)
    SELECT
        id,
        spring_session_primary_id,
        status,
        is_active,
        created_at,
        items_count,
        items_quantity,
        order_total,
        users_user_id
    FROM
        springapp.bcp_orders;

CREATE UNIQUE INDEX orders__idx ON
    orders (
        id
    ASC )
        LOGGING;

CREATE UNIQUE INDEX orders__idxv1 ON
    orders (
        spring_session_primary_id
    ASC )
        LOGGING;

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( id );
CREATE TABLE products (
    id            INTEGER NOT NULL,
    category_id   INTEGER NOT NULL,
    part_number   VARCHAR2(255 BYTE),
    description   VARCHAR2(255 BYTE) NOT NULL,
    service       VARCHAR2(10 BYTE),
    price         NUMBER(19, 2) NOT NULL
)
LOGGING;

CREATE UNIQUE INDEX products__idx ON
    products (
        id
    ASC )
        LOGGING;

ALTER TABLE products ADD CONSTRAINT products_pk PRIMARY KEY ( id );

CREATE SEQUENCE products_id_seq START WITH 19000 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER products_id_trg BEFORE
    INSERT ON products
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := products_id_seq.nextval;
END;
/
DROP INDEX springapp.spring_session_ix2;

DROP INDEX springapp.spring_session_ix3;

ALTER TABLE springapp.spring_session RENAME TO bcp_spring_session;

CREATE TABLE spring_session (
    primary_id              CHAR(36 BYTE) NOT NULL,
    session_id              CHAR(36 BYTE) NOT NULL,
    creation_time           NUMBER(19) NOT NULL,
    last_access_time        NUMBER(19) NOT NULL,
    max_inactive_interval   NUMBER(10) NOT NULL,
    expiry_time             NUMBER(19) NOT NULL,
    principal_name          VARCHAR2(100 CHAR)
)

logging;

INSERT INTO spring_session (
    primary_id,
    session_id,
    creation_time,
    last_access_time,
    max_inactive_interval,
    expiry_time,
    principal_name
)
    SELECT
        primary_id,
        session_id,
        creation_time,
        last_access_time,
        max_inactive_interval,
        expiry_time,
        principal_name
    FROM
        springapp.bcp_spring_session;

CREATE UNIQUE INDEX spring_session_ix1 ON
    spring_session (
        session_id
    ASC )
        LOGGING;

CREATE INDEX spring_session_ix2 ON
    spring_session (
        expiry_time
    ASC )
        LOGGING;

CREATE INDEX spring_session_ix3 ON
    spring_session (
        principal_name
    ASC )
        LOGGING;

CREATE UNIQUE INDEX spring_session_pk ON
    spring_session (
        primary_id
    ASC )
        LOGGING;

ALTER TABLE spring_session ADD CONSTRAINT spring_session_pk PRIMARY KEY ( primary_id );
ALTER TABLE springapp.spring_session_attributes DROP CONSTRAINT spring_session_attributes_pk CASCADE;

DROP INDEX springapp.spring_session_attributes_pk;

ALTER TABLE springapp.spring_session_attributes RENAME TO bcp_spring_session_attributes;

CREATE TABLE spring_session_attributes (
    session_primary_id          CHAR(36 BYTE) NOT NULL,
    attribute_name              VARCHAR2(200 CHAR) NOT NULL,
    attribute_bytes             BLOB NOT NULL,
    spring_session_primary_id   CHAR(36 BYTE) NOT NULL
)

logging;

INSERT INTO spring_session_attributes (
    session_primary_id,
    attribute_name,
    attribute_bytes,
    spring_session_primary_id
)
    SELECT
        session_primary_id,
        attribute_name,
        attribute_bytes,
        spring_session_primary_id
    FROM
        springapp.bcp_spring_session_attributes;

CREATE UNIQUE INDEX spring_session_attributes_pk ON
    spring_session_attributes (
        session_primary_id
    ASC,
        attribute_name
    ASC )
        LOGGING;

ALTER TABLE spring_session_attributes ADD CONSTRAINT spring_session_attributes_pk PRIMARY KEY ( session_primary_id,
                                                                                                attribute_name );
CREATE TABLE users (
    user_id         INTEGER NOT NULL,
    email           VARCHAR2(255) NOT NULL,
    first_name      VARCHAR2(255) NOT NULL,
    last_name       VARCHAR2(255),
    password_hash   VARCHAR2(255),
    status          INTEGER,
    created_at      TIMESTAMP DEFAULT systimestamp
)
LOGGING;

CREATE UNIQUE INDEX users__idx ON
    users (
        user_id
    ASC )
        LOGGING;

CREATE UNIQUE INDEX users__idxv1 ON
    users (
        email
    ASC )
        LOGGING;

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( user_id );

CREATE SEQUENCE users_user_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER users_user_id_trg BEFORE
    INSERT ON users
    FOR EACH ROW
    WHEN ( new.user_id IS NULL )
BEGIN
    :new.user_id := users_user_id_seq.nextval;
END;
/
ALTER TABLE categories
    ADD CONSTRAINT categories_categories_fk FOREIGN KEY ( parent_id )
        REFERENCES categories ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;


-- Error while generating DDL for ORDER_ITEMS_PRODUCTS_FK (ORDER_DETAILS : PRODUCTS ). See log file for details.

ALTER TABLE order_details
    ADD CONSTRAINT order_items_orders_fk FOREIGN KEY ( orders_id )
        REFERENCES orders ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;


-- Error while generating DDL for ORDERS_USERS_FK (ORDERS : USERS ). See log file for details.

ALTER TABLE orders
    ADD CONSTRAINT orders_spring_session_fk FOREIGN KEY ( spring_session_primary_id )
        REFERENCES spring_session ( primary_id )
    NOT DEFERRABLE;
ALTER TABLE products
    ADD CONSTRAINT products_categories_fk FOREIGN KEY ( category_id )
        REFERENCES categories ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;
ALTER TABLE spring_session_attributes
    ADD CONSTRAINT spring_session_attributes_fk FOREIGN KEY ( spring_session_primary_id )
        REFERENCES spring_session ( primary_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                            14
-- CREATE VIEW                              0
-- ALTER TABLE                             20
-- ALTER INDEX                              0
-- ALTER VIEW                               0
-- DROP TABLE                               0
-- DROP INDEX                               7
-- DROP VIEW                                0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- DROP PACKAGE                             0
-- DROP PACKAGE BODY                        0
-- DROP PROCEDURE                           0
-- DROP FUNCTION                            0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- DROP TRIGGER                             0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- DROP TYPE                                0
-- CREATE SEQUENCE                          5
-- ALTER SEQUENCE                           0
-- DROP SEQUENCE                            0
-- CREATE MATERIALIZED VIEW                 0
-- DROP MATERIALIZED VIEW                   0
-- CREATE SYNONYM                           0
-- DROP SYNONYM                             0
-- CREATE DIMENSION                         0
-- DROP DIMENSION                           0
-- CREATE CONTEXT                           0
-- DROP CONTEXT                             0
-- CREATE DIRECTORY                         0
-- DROP DIRECTORY                           0

-- 
-- ERRORS                                   2
-- WARNINGS                                 0
